	-- SEQUENCIAS

DROP SEQUENCE SQ_DIN_CIDADE;
DROP SEQUENCE SQ_DIN_ENDERECO;
DROP SEQUENCE SQ_DIN_ENTREGA;
DROP SEQUENCE SQ_DIN_ENTREGA_ENDERECO;
DROP SEQUENCE SQ_DIN_ESTADO;
DROP SEQUENCE SQ_DIN_PACOTE;
DROP SEQUENCE SQ_DIN_TELEFONE;
DROP SEQUENCE SQ_DIN_USUARIO;
CREATE SEQUENCE SQ_DIN_CIDADE START WITH 1;
CREATE SEQUENCE SQ_DIN_ENDERECO START WITH 1;
CREATE SEQUENCE SQ_DIN_ENTREGA START WITH 1;
CREATE SEQUENCE SQ_DIN_ENTREGA_ENDERECO START WITH 1;
CREATE SEQUENCE SQ_DIN_ESTADO START WITH 1;
CREATE SEQUENCE SQ_DIN_PACOTE START WITH 1;
CREATE SEQUENCE SQ_DIN_TELEFONE START WITH 1;
CREATE SEQUENCE SQ_DIN_USUARIO START WITH 1;

-- ESTADOS

INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Acre','AC');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Alagoas','AL');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Amapá','AP');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Amazonas','AM');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Bahia','BA');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Ceará','CE');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Distrito Federal','DF');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Espírito Santo','ES');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Goiás','GO');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Maranhão','MA');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Mato Grosso','MT');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Mato Grosso do Sul','MS');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Minas Gerais','MG');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Pará','PA');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Paraíba','PB');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Paraná','PR');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Pernambuco','PE');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Piauí','PI');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Rio de Janeiro','RJ');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Rio Grande do Norte','RN');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Rio Grande do Sul','RS');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Rondônia','RO');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Roraima','RR');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Santa Catarina','SC');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'São Paulo','SP');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Sergipe','SE');
INSERT INTO T_DIN_ESTADO(ID_ESTADO,NM_ESTADO,SG_ESTADO) VALUES (SQ_DIN_ESTADO.NEXTVAL,'Tocantins','TO');

-- CIDADES

DROP SEQUENCE SQ_DIN_ESTADO;
CREATE SEQUENCE SQ_DIN_ESTADO START WITH 1;

INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Rio Branco');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Sena Madureira');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Maceió');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Arapiraca');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Macapa');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Oiapoque');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Manaus');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Manacapuru');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Salvador');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Feira de Santana');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Fortaleza');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Juazeiro do Norte');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Brasília');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Ceilândia');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Vitória');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Guarapari');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Goiânia');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Anápolis');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'São Luís');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Imperatriz');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Cuiabá');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Tangará da Serra');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Campo Grande');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Dourados');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Belo Horizonte');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Ouro Preto');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Belém');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Altamira');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'João Pessoa');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Patos');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Curitiba');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Londrina');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Recife');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Olinda');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Teresina');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Parnaíba');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Rio de Janeiro');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Petrópolis');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Natal');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Mossoró');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Porto Alegre');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Pelotas');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Porto Velho');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Ariquemes');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Boa vista');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Rorainópolis');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Florianópolis');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Blumenau');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'São Paulo');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Campinas');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Aracaju');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Lagarto');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.NEXTVAL,'Palmas');
INSERT INTO T_DIN_CIDADE(ID_CIDADE,ID_ESTADO,NM_CIDADE) VALUES(SQ_DIN_CIDADE.NEXTVAL,SQ_DIN_ESTADO.CURRVAL,'Gurupi');

-- ENDERECOS

INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),64212115,'Rua Venezuela',(DBMS_RANDOM.VALUE(0000,99999)),'Apto 48', 'Em frente ao posto');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),57086032,'Quadra 2',(DBMS_RANDOM.VALUE(0000,99999)),'Andar 1', NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),49089456,'Rua N',(DBMS_RANDOM.VALUE(0000,99999)),'Fundos','Portão cinza');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),92320470,'Rua das Rosas',(DBMS_RANDOM.VALUE(0000,99999)),'Terreo', NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),82415110,'Rua Severino Tessari',(DBMS_RANDOM.VALUE(0000,99999)),'Quadra 6', NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),67035135,'Alameda Onça',(DBMS_RANDOM.VALUE(0000,99999)),'Conjunto 9','Porta azul');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),98015620,'Rua Sergipe',(DBMS_RANDOM.VALUE(0000,99999)),'Quadra 8','Portão roxo');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),69903700,'Rua Sobral',(DBMS_RANDOM.VALUE(0000,99999)),'Piso 5', NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),86706665,'Rua Pintadinho',(DBMS_RANDOM.VALUE(0000,99999)),'Casa 3',NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),69060106,'Rua Orleans',(DBMS_RANDOM.VALUE(0000,99999)),'Apto 78',NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),69903040,'Travessa Portela',(DBMS_RANDOM.VALUE(0000,99999)),NULL,'Aeroporto 8');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),90843463,'Acesso G-Quatro',(DBMS_RANDOM.VALUE(0000,99999)),'Apto 14',NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),59607230,'Rua Francisco Heronildes',(DBMS_RANDOM.VALUE(0000,99999)),NULL,'Portão preto');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),73402389,'Conjunto Conjunto M',(DBMS_RANDOM.VALUE(0000,99999)),'apto 99','Edifício Ruivo Lima');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),67140410,'Travessa WE-04',(DBMS_RANDOM.VALUE(0000,99999)),NULL,NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),18170000,'Rua das Perobeiras',(DBMS_RANDOM.VALUE(0000,99999)),NULL,'casa rosa');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),69316034,'Travessa Estrela Bonita',(DBMS_RANDOM.VALUE(0000,99999)),NULL,'Aeroporto 8');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),04143030,'Rua Dias de Toledo',(DBMS_RANDOM.VALUE(0000,99999)),'Sala 7', NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),58053160,'Rua Maestro Renato Elesbão',(DBMS_RANDOM.VALUE(0000,99999)),'Salão 12',NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),90230080,'Praça Pinheiro Machado',(DBMS_RANDOM.VALUE(0000,99999)),NULL,'Em frente ao hospital');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),94470220,'Rua Santarém',(DBMS_RANDOM.VALUE(0000,99999)),'Conjunto 2','Porta cinza');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),76872850,'Travessa Jorge Teixeira',(DBMS_RANDOM.VALUE(0000,99999)),NULL,'Em cima da padaria');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),29179011,'Rua Cupiaba',(DBMS_RANDOM.VALUE(0000,99999)),'Galeria 10',NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),74482150,'Rodovia GO 70',(DBMS_RANDOM.VALUE(0000,99999)),'Quadra 1',NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),54766075,'Rua Major Araci',(DBMS_RANDOM.VALUE(0000,99999)),NULL,'de frente com a pizzaria');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),24735390,'Rua Jaime Devilat dos Santos',(DBMS_RANDOM.VALUE(0000,99999)),NULL,NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),69316038,'Rua Z-Y',(DBMS_RANDOM.VALUE(0000,99999)),'Galpão 3',NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),49047460,'Rua Santa Terezinha',(DBMS_RANDOM.VALUE(0000,99999)),'Anexo 4',NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),68745470,'Travessa Major R. Passarinho',(DBMS_RANDOM.VALUE(0000,99999)),'Anexo 11','ultima casa da rua');
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),59022500,'Rua Joaquim Fagundes',(DBMS_RANDOM.VALUE(0000,99999)),'Lote 6',NULL);
INSERT INTO T_DIN_ENDERECO(ID_ENDERECO,ID_CIDADE,NR_CEP,NM_LOGRADOURO,NR_LOGRADOURO,DS_COMPLEMENTO,DS_REFERENCIA) VALUES(SQ_DIN_ENDERECO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(1,54)),89810824,'Rua das Araucárias',(DBMS_RANDOM.VALUE(0000,99999)),'Conjunto 10','Galpão vermelho');

-- 1o commit referente aos endereços

COMMIT;

-- USUARIOS

INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'patricia.ferreira@gmail.com','F6jTRTzQkD','Patrícia Bianca Ferreira',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'analu-oliveira76@gmail.com','7pbinLJnTG','Analu Oliveira',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'sabrina-sales90@gmail.com','BE8h6NN4cq','Sabrina Lorena Sales',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'ruanbeneditodacunha@gmail.com','7pbinCLnTG','Ruan Nelson da Cunha',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'eduardo.vieira@gmail.com','FqQkLIFoXE','Eduardo Emanuel Vieira',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'tiago_silva56@gmail.com','DXPHD18u5S','Tiago Mateus Silva',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'kamilly.campos72@gmail.com','Fys8Z95bQ3','Sara Kamilly Louise Campos',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'oliver_baptista@gmail.com','pcJG8puRxy','Oliver Baptista',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'marcosvrodrigues@gmail.com','8YaJlfLoN2','Marcos Vinicius Rodrigues',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'isisluizaramos@gmail.com','7aykINNCig','Isis Luiza Ramos',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'vanessa-souza74@gmail.com','tKY3ZO7q0e','Vanessa Isabela Souza',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'felipe_rezende44@gmail.com','Hu9mktrJpd','Felipe Vinicius Rezende',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));
INSERT INTO T_DIN_USUARIO(ID_USUARIO,NR_CPF,DS_EMAIL,DS_SENHA,NM_USUARIO,DT_NASCIMENTO) VALUES (SQ_DIN_USUARIO.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(40000000000,99999999999)),'jojoconda@gmail.com','7aykIGGCig','Joana Conda',SYSDATE-DBMS_RANDOM.VALUE(6570,20440));

-- TELEFONE

DROP SEQUENCE SQ_DIN_USUARIO;
CREATE SEQUENCE SQ_DIN_USUARIO START WITH 1;

INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));
INSERT INTO T_DIN_TELEFONE(ID_USUARIO,ID_TELEFONE,NR_DDD,NR_TELEFONE) VALUES (SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_TELEFONE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(11,99)),TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)));

-- 2o commit referente aos usuários

COMMIT;

-- PACOTE

INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'McLancheFeliz','A');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Vestido e saia','V');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Remedios para ansiedade','R');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Envelopes','D');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Aborora de Halloween','O');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Documentação da casa','D');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Chave de fenda, chave inglesa e alicate','O');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Boneca baby Alive','O');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'3 camisetas do São Paulo','V');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Benegrip, Diazepam e rivotril','R');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Boneco do MaxSteel','O');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Colar de Pérolas','F');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Cerâmica','F');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Luvas de golf','V');
INSERT INTO T_DIN_PACOTE(ID_PACOTE,VL_PESO,VL_ALTURA,VL_LARGURA,VL_COMPRIMENTO,DS_CONTEUDO,TP_CONTEUDO) VALUES (SQ_DIN_PACOTE.NEXTVAL,TRUNC(DBMS_RANDOM.VALUE(0.1,2.5),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),TRUNC(DBMS_RANDOM.VALUE(0.1,30),2),'Bolo de Chocolate, Resfenol e uma carta','X');

-- ENTREGA

DROP SEQUENCE SQ_DIN_PACOTE;
DROP SEQUENCE SQ_DIN_USUARIO;
CREATE SEQUENCE SQ_DIN_PACOTE START WITH 1;
CREATE SEQUENCE SQ_DIN_USUARIO START WITH 1;

INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'X');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'N');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),SYSDATE,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'C');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),SYSDATE,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'C');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'V');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),SYSDATE,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'C');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'V');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.CURRVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),SYSDATE,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'C');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'N');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'N');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'N');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.CURRVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'X');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'X');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE-DBMS_RANDOM.VALUE(0.1,2),NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'V');
INSERT INTO T_DIN_ENTREGA(ID_ENTREGA,ID_USUARIO,ID_PACOTE,DT_PEDIDO,DT_CONCLUSAO,VL_PRECO,VL_DISTANCIA,ST_ENTREGA) VALUES (SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_USUARIO.NEXTVAL,SQ_DIN_PACOTE.NEXTVAL,SYSDATE,NULL,TRUNC(DBMS_RANDOM.VALUE(9.9,67),2),TRUNC(DBMS_RANDOM.VALUE(0.1,25),1),'V');

-- ENTREGA_ENDEREÇO

DROP SEQUENCE SQ_DIN_ENDERECO;
DROP SEQUENCE SQ_DIN_ENTREGA;
CREATE SEQUENCE SQ_DIN_ENDERECO START WITH 1;
CREATE SEQUENCE SQ_DIN_ENTREGA START WITH 1;

INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Paulo',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Patrícia',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Roberto',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Thomas',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Caio',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Daniel',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Gabriela',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Vitor',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Luiza',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Leo',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Gabriel',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'João',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Felipe',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Daiana',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Igor',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Guilherme',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Benedito',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Fabio',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Carlos',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Tiago',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Isadora',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Sabrina',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Gustavo',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Rafaela',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Estela',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Gabriel',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Carol',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'João',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.NEXTVAL,SQ_DIN_ENDERECO.NEXTVAL,'Luan',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'R');
INSERT INTO T_DIN_ENTREGA_ENDERECO(ID_ENTREGA_ENDERECO,ID_ENTREGA,ID_ENDERECO,NM_RESPONSAVEL,NR_TEL_RESPONSAVEL,TP_ENDERECO) VALUES(SQ_DIN_ENTREGA_ENDERECO.NEXTVAL,SQ_DIN_ENTREGA.CURRVAL,SQ_DIN_ENDERECO.NEXTVAL,'Maria',TRUNC(DBMS_RANDOM.VALUE(11,99))||TRUNC(DBMS_RANDOM.VALUE(900000000,999999999)),'D');

-- 3o commit referente às entregas

COMMIT;