--- ALTERAÇÕES M

DROP TABLE t_din_cidade CASCADE CONSTRAINTS;

DROP TABLE t_din_endereco CASCADE CONSTRAINTS;

DROP TABLE t_din_entrega CASCADE CONSTRAINTS;

DROP TABLE t_din_entrega_endereco CASCADE CONSTRAINTS;

DROP TABLE t_din_estado CASCADE CONSTRAINTS;

DROP TABLE t_din_pacote CASCADE CONSTRAINTS;

DROP TABLE t_din_telefone CASCADE CONSTRAINTS;

DROP TABLE t_din_usuario CASCADE CONSTRAINTS;



CREATE TABLE t_din_cidade (
    id_cidade NUMBER(9) NOT NULL,
    id_estado NUMBER(9) NOT NULL,
    nm_cidade VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN t_din_cidade.id_cidade IS
    'ID_CIDADE - ESSA COLUNA SERVE PARA ARMAZENAR O ID DA CIDADE, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_cidade.nm_cidade IS
    'NM_CIDADE - ESSA COLUNA SERVE PARA ARMAZENAR O NOME DA CIDADE, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO
';

ALTER TABLE t_din_cidade ADD CONSTRAINT t_din_cidade_pk PRIMARY KEY ( id_cidade );

CREATE TABLE t_din_endereco (
    id_endereco    NUMBER(9) NOT NULL,
    id_cidade      NUMBER(9) NOT NULL,
    nr_cep         NUMBER(8) NOT NULL,
    nm_logradouro  VARCHAR2(30) NOT NULL,
    nr_logradouro  NUMBER(5) NOT NULL,
    ds_complemento VARCHAR2(80),
    ds_referencia  VARCHAR2(80)
);

COMMENT ON COLUMN t_din_endereco.id_endereco IS
    'ID_ENDERECO - ESSA COLUNA SERVE PARA ARMAZENAR O ID DO ENDEREÇO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_endereco.nr_cep IS
    'NR_CEP - ESTE ATRIBUTO SERVE PARA ARMAZENAR O CEP DO ENDEREÇO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_endereco.nm_logradouro IS
    'NM_LOGRADOURO - ESSA COLUNA SERVE PARA ARMAENAR O NOME DO LOGRADOURO DO ENDEREÇO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_endereco.nr_logradouro IS
    'NR_LOGRADOURO - ESSA COLUNA SERVE PARA ARMAZENAR O NÚMERO DO LOGRADOURO DO ENDEREÇO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_endereco.ds_complemento IS
    'DS_COMPLEMENTO - ESSA COLUNA SERVE PARA ARMAZENAR A DESCRIÇÃO DO COMPLEMENTO DO ENDEREÇO, ESTE CAMPO É OPCIONAL E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_endereco.ds_referencia IS
    'DS_REFERENCIA - ESSA COLUNA SERVE PARA ARMAZENAR A DESCRIÇÃO DA REFERÊNCIA DO ENDEREÇO, ESTE CAMPO É OPCIONAL E É PREENCHIDO PELO USUÁRIO
';

ALTER TABLE t_din_endereco ADD CONSTRAINT t_din_endereco_pk PRIMARY KEY ( id_endereco );

CREATE TABLE t_din_entrega (
    id_entrega   NUMBER(9) NOT NULL,
    id_usuario   NUMBER(9) NOT NULL,
    id_pacote    NUMBER(9) NOT NULL,
    dt_pedido    DATE NOT NULL,
    dt_conclusao DATE,
    vl_preco     NUMBER(7, 2) NOT NULL,
    vl_distancia NUMBER(4, 1) NOT NULL,
    st_entrega   CHAR(1) NOT NULL
);

ALTER TABLE t_din_entrega
    ADD CONSTRAINT ck_confirmacao CHECK ( st_entrega IN ( 'C', 'X', 'N', 'V' ) );

COMMENT ON COLUMN t_din_entrega.id_entrega IS
    'ID_ENTREGA - ESSA COLUNA SERVE PARA ARMAZENAR O ID DA ENTREGA, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_entrega.id_usuario IS
    'DT_PEDIDO - ESSA COLUNA SERVE PARA ARMAZENAR A DATA DO PEDIDO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_entrega.dt_pedido IS
    'DT_PEDIDO - ESSA COLUNA SERVE PARA ARMAZENAR A DATA DO PEDIDO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_entrega.dt_conclusao IS
    'DT_CONCLUSAO - ESSA COLUNA SERVE PARA ARMAZENAR DATA DE CONCLUSAO DO PEDIDO, ESSE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_entrega.vl_preco IS
    'VL_PRECO - ESSA COLUNA SERVE PARA ARMAZENAR DATA DE PREVISÃO DO PEDIDO, ESSE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_entrega.vl_distancia IS
    'VL_DISTANCIA - ESSA COLUNA SERVE PARA ARMAZENAR DATA DE PREVISÃO DO PEDIDO, ESSE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_entrega.st_entrega IS
    'ST_ENTREGA - ESSA COLUNA SERVE PARA ARMAZENAR A CONFIRMAÇÃO PARA O POUSO DO DRONE, ESSE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE. OS VALORES POSSÍVEIS PARA ESTE ATRIBUTO É "C" PARA CONCLUIDO,"X" PARA CANCELADO, "N" PARA NÃO ACEITO E "V" PARA EM VIAGEM
';

ALTER TABLE t_din_entrega ADD CONSTRAINT t_din_entrega_pk PRIMARY KEY ( id_entrega );

CREATE TABLE t_din_entrega_endereco (
    id_entrega_endereco NUMBER(9) NOT NULL,
    id_entrega          NUMBER(9) NOT NULL,
    id_endereco         NUMBER(9) NOT NULL,
    nm_responsavel      VARCHAR2(30) NOT NULL,
    nr_tel_responsavel  NUMBER(11) NOT NULL,
    tp_endereco         CHAR(1 CHAR) NOT NULL
);

COMMENT ON COLUMN t_din_entrega_endereco.id_entrega_endereco IS
    'ID_ENTREGA_ENDERECO - ESSA COLUNA SERVE PARA ARMAZENAR O ID DA TABELA ASSOCIATIVA ENTRE AS COLUNAS T_DIN_ENTREGA E T_DIN_ENDERECO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_entrega_endereco.nm_responsavel IS
    'NM_RESPONSAVEL - ESSA COLUNA SERVE PARA ARMAZENAR O NOME DO RESPONSÁVEL PELO RECEBIMENTO OU ENVIO, ESTE CAMPO É OPCIONAL E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_entrega_endereco.nr_tel_responsavel IS
    'NR_TEL_RESPONSAVEL - ESSA COLUNA SERVE PARA ARMAZENAR O TELEFONE DO RESPONSÁVEL PELO RECEBIMENTO OU ENVIO, ESTE CAMPO É OPCIONAL E É PREENCHIDO PELO USUÁRIO';

COMMENT ON COLUMN t_din_entrega_endereco.tp_endereco IS
    'TP_ENDERECO - ATRIBUTO OBRIGATORIO COM VALORES ''R'' DE REMETENTE E ''D'' DE DESTINATARIO';

ALTER TABLE t_din_entrega_endereco ADD CONSTRAINT t_din_entrega_endereco_pk PRIMARY KEY ( id_entrega_endereco );

CREATE TABLE t_din_estado (
    id_estado NUMBER(9) NOT NULL,
    nm_estado VARCHAR2(30) NOT NULL,
    sg_estado CHAR(2) NOT NULL
);

COMMENT ON COLUMN t_din_estado.id_estado IS
    'ID_ESTADO - ESSA COLUNA SERVE PARA ARMAZENAR O ID DO ESTADO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_estado.nm_estado IS
    'NM_ESTADO - ESSA COLUNA SERVE PARA ARMAZENAR O NOME DO ESTADO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_estado.sg_estado IS
    'SG_ESTADO- ESSE ATRIBUTO ARMAZENA A SIGLA DO ESTADO E É OBRIGATÓRIO';

ALTER TABLE t_din_estado ADD CONSTRAINT t_din_estado_pk PRIMARY KEY ( id_estado );

CREATE TABLE t_din_pacote (
    id_pacote      NUMBER(9) NOT NULL,
    vl_peso        NUMBER(3, 2) NOT NULL,
    vl_altura      NUMBER(4, 2) NOT NULL,
    vl_largura     NUMBER(4, 2) NOT NULL,
    vl_comprimento NUMBER(4, 2) NOT NULL,
    ds_conteudo    VARCHAR2(300),
    tp_conteudo    CHAR(1) NOT NULL
);

ALTER TABLE t_din_pacote
    ADD CHECK ( vl_peso BETWEEN 0.01 AND 2.5 );

ALTER TABLE t_din_pacote
    ADD CHECK ( vl_altura BETWEEN 0.01 AND 30 );

ALTER TABLE t_din_pacote
    ADD CHECK ( vl_largura BETWEEN 0.01 AND 30 );

ALTER TABLE t_din_pacote
    ADD CHECK ( vl_comprimento BETWEEN 0.01 AND 30 );

ALTER TABLE t_din_pacote
    ADD CHECK ( tp_conteudo IN ( 'A', 'D', 'F', 'O', 'R',
                                 'V', 'X' ) );

COMMENT ON COLUMN t_din_pacote.id_pacote IS
    'ID_PACOTE - ESSA COLUNA SERVE PARA ARMAZENAR O ID DO PACOTE, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_pacote.vl_peso IS
    'VL_PESO - ESSA COLUNA SERVE PARA ARMAZENAR O PESO DO PRODUTO EM GRAMAS, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_pacote.vl_altura IS
    'VL_ALTURA - ESSA COLUNA SERVE PARA ARMAZENAR A ALTURA DO PACOTE, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_pacote.vl_largura IS
    'VL_LARGURA- ESSA COLUNA SERVE PARA ARMAZENAR A LARGURA DO PACOTE, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_pacote.vl_comprimento IS
    'VL_COMPRIMENTO- ESSA COLUNA SERVE PARA ARMAZENAR A COMPRIMENTO DO PACOTE, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO
';

COMMENT ON COLUMN t_din_pacote.ds_conteudo IS
    'DS_CONTEUDO - ESSA COLUNA SERVE PARA ARMAZENAR O ID DO CONTEUDO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_pacote.tp_conteudo IS
    'TP_CONTEUDO - ESSA COLUNA SERVE PARA ARMZENAR QUAL É O TIPO DO CONTEUDO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO USUÁRIO. OS VALORES POSSÍVEIS PARA ESTE ATRIBUTO SÃO "A" PARA ALIMENTOS, "D" PARA DOCUMENTOS, "F" PARA FRÁGEIS, "O" PARA OBJETOS, "R" PARA REMÉDIOS, "V" PARA VESTUÁRIOS E "X" ÁRA OUTROS ';

ALTER TABLE t_din_pacote ADD CONSTRAINT t_din_produto_pk PRIMARY KEY ( id_pacote );

CREATE TABLE t_din_telefone (
    id_usuario  NUMBER(9) NOT NULL,
    id_telefone NUMBER(9) NOT NULL,
    nr_ddd      NUMBER(3) NOT NULL,
    nr_telefone NUMBER(11) NOT NULL
);

COMMENT ON COLUMN t_din_telefone.id_telefone IS
    'ID_TELEFONE- ATRIBUTO PRINCIPAL E OBRIGATÓRIO, TRATA-SE DO ID DO TELEFONE DO USUARIO CADASTRADO.';

COMMENT ON COLUMN t_din_telefone.nr_ddd IS
    'NR_DDD-ATRIBUTO E OBRIGATÓRIO, TRATA-SE DO CODIGO DO DDD DO TELEFONE DO USUARIO CADASTRADO.';

COMMENT ON COLUMN t_din_telefone.nr_telefone IS
    'NR_TELEFONE- ATRIBUTO OBRIGATÓRIO, TRATA-SE DO NUMERO DE TELEFONE DO USUARIO CADASTRADO.';

ALTER TABLE t_din_telefone ADD CONSTRAINT t_din_telefone_pk PRIMARY KEY ( id_telefone,
                                                                          id_usuario );

CREATE TABLE t_din_usuario (
    id_usuario    NUMBER(9) NOT NULL,
    nr_cpf        NUMBER(11) NOT NULL,
    ds_email      VARCHAR2(40) NOT NULL,
    ds_senha      VARCHAR2(30) NOT NULL,
    nm_usuario    VARCHAR2(30) NOT NULL,
    dt_nascimento DATE NOT NULL
);

COMMENT ON COLUMN t_din_usuario.id_usuario IS
    'ID_USUÁRIO - ESSA COLUNA SERVE PARA ARMAZENAR O ID DO USUÁRIO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO AUTOMATICAMENTE
';

COMMENT ON COLUMN t_din_usuario.nr_cpf IS
    'NR_CPF - ESSA COLUNA SERVE PARA ARMZENAR O CPF DO USUÁRIO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO  USUÁRIO
';

COMMENT ON COLUMN t_din_usuario.ds_email IS
    'DS_EMAIL - ESSA COLUNA SERVE PARA ARMEZENAR O EMAIL DO USUÁRIO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO  USUÁRIO
';

COMMENT ON COLUMN t_din_usuario.ds_senha IS
    'DS_SENHA - ESSA COLUNA SERVE PARA ARMAZENAR O EMAIL DO USÁRIO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO  USUÁRIO
';

COMMENT ON COLUMN t_din_usuario.nm_usuario IS
    'NM_USUÁRIO - ESSA COLUNA SERVE PARA ARMZENAR O NOME DO USUÁRIO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO  USUÁRIO
';

COMMENT ON COLUMN t_din_usuario.dt_nascimento IS
    'DT_NASCIMENTO - ESSA COLUNA SERVE PARA ARMAZENAR A DATA DE NASCIMENTO DO USUÁRIO, ESTE CAMPO É OBRIGATÓRIO E É PREENCHIDO PELO  USUÁRIO
';

ALTER TABLE t_din_usuario ADD CONSTRAINT t_din_usuario_pk PRIMARY KEY ( id_usuario );

ALTER TABLE t_din_usuario ADD CONSTRAINT uk_din_usuario_nr_cpf UNIQUE ( nr_cpf );

ALTER TABLE t_din_usuario ADD CONSTRAINT uk_din_usuario_ds_email UNIQUE ( ds_email );

ALTER TABLE t_din_endereco
    ADD CONSTRAINT fk_cidade_endereco FOREIGN KEY ( id_cidade )
        REFERENCES t_din_cidade ( id_cidade );

ALTER TABLE t_din_entrega_endereco
    ADD CONSTRAINT fk_endereco_entrega FOREIGN KEY ( id_endereco )
        REFERENCES t_din_endereco ( id_endereco );

ALTER TABLE t_din_entrega_endereco
    ADD CONSTRAINT fk_entrega_endereco FOREIGN KEY ( id_entrega )
        REFERENCES t_din_entrega ( id_entrega );

ALTER TABLE t_din_cidade
    ADD CONSTRAINT fk_estado_cidade FOREIGN KEY ( id_estado )
        REFERENCES t_din_estado ( id_estado );

ALTER TABLE t_din_entrega
    ADD CONSTRAINT fk_pacote_entrega FOREIGN KEY ( id_pacote )
        REFERENCES t_din_pacote ( id_pacote );

ALTER TABLE t_din_entrega
    ADD CONSTRAINT fk_usuario_entrega FOREIGN KEY ( id_usuario )
        REFERENCES t_din_usuario ( id_usuario );

ALTER TABLE t_din_telefone
    ADD CONSTRAINT fk_usuario_telefone FOREIGN KEY ( id_usuario )
        REFERENCES t_din_usuario ( id_usuario );
